# Generated by Django 2.2.1 on 2019-06-10 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='Image',
            field=models.ImageField(blank=True, upload_to='profile_image'),
        ),
    ]
