# Generated by Django 2.2.1 on 2019-06-22 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_student_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='Image',
            new_name='image',
        ),
    ]
